# Generated by Django 6.0.2 on 2026-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
